### ISSUE TITLE
button borders should align

### ISSUE THREAD

**Issue by samuwen** [AhoyLemon/wrongest.website#9]
The two buttons on the page (top and bottom) have different borders. We should have them align (to whatever)

**Comment by AhoyLemon** [comment]
I don't get what you mean, align to what? Both buttons are using the same exact classes.

**Comment by samuwen** [comment]
the bottom button has a black border, top button does not. Align as in "look similar in construction"

**Comment by AhoyLemon** [comment]
I see what you're saying now. The border color is actually the same color as the color I'm using on the top screen, so the buttons read differently.

I made the button borders fully black (#000000) for now, which I don't particularly love doing, since I'm not using that color anywhere else, but it's the only solution for now.

**Comment by AhoyLemon** [comment]
[1ae8380]
